import type { Locale } from '@/lib/i18n';

export type ContentPage = {
  slug: string;
  source?: string;
  image: string;
  imageFit?: 'cover' | 'contain';
  imagePosition?: string;
  imageScale?: number;
  imageTransformOrigin?: string;
  kicker: Record<Locale, string>;
  title: Record<Locale, string>;
  summary: Record<Locale, string>;
  group: 'history' | 'knowledge' | 'main';
};

export const contentPages: ContentPage[] = [
  {
    slug: 'about',
    source: 'about.md',
    image: '/media/about/generations-group.jpg',
    imagePosition: 'center 38%',
    kicker: { sv: 'Robert “Rob-One” Wägars väg till Locking', en: 'Robert “Rob-One” Wägar’s journey into Locking', fr: 'Le parcours de Robert « Rob-One » Wägar dans le Locking', fi: 'Robert ”Rob-One” Wägarin matka Lockingin pariin', es: 'El camino de Robert “Rob-One” Wägar hacia el Locking', pt: 'A jornada de Robert “Rob-One” Wägar no Locking', ko: 'Robert “Rob-One” Wägar가 락킹을 만나온 여정', ja: 'Robert “Rob-One” Wägarとロッキングの歩み', zh: 'Robert “Rob-One” Wägar 与 Locking 的旅程' },
    title: { sv: 'Om Locking.se', en: 'About Locking.se', fr: 'À propos de Locking.se', fi: 'Tietoa Locking.se-sivustosta', es: 'Acerca de Locking.se', pt: 'Sobre a Locking.se', ko: 'Locking.se 소개', ja: 'Locking.seについて', zh: '关于 Locking.se' },
    summary: {
      sv: 'Min personliga berättelse om Locking, människorna jag mött och sökandet efter kunskap – från 1980-talet till idag.',
      en: 'My personal story of Locking, the people I have met, and the search for knowledge – from the 1980s to today.',
      fr: 'Mon histoire personnelle avec le Locking, les rencontres et la quête de connaissances, des années 1980 à aujourd’hui.',
      fi: 'Henkilökohtainen tarinani Lockingista, kohtaamistani ihmisistä ja tiedon etsimisestä – 1980-luvulta tähän päivään.',
      es: 'Mi historia personal con el Locking, las personas que conocí y la búsqueda de conocimiento desde los años 80 hasta hoy.',
      pt: 'Minha história pessoal com o Locking, as pessoas que conheci e a busca por conhecimento — dos anos 80 até hoje.',
      ko: '1980년대부터 오늘까지, 락킹과 내가 만난 사람들, 그리고 지식을 찾아온 여정에 대한 개인적인 이야기입니다.',
      ja: '1980年代から今日まで、ロッキング、出会ってきた人々、そして知識を求めてきた歩みについての個人的な物語です。',
      zh: '从1980年代至今，我与 Locking、一路遇见的人，以及寻找知识的个人故事。',
    },
    group: 'main',
  },
  {
    slug: 'history',
    source: 'history.md',
    image: '/media/mavericksflat.png',
    kicker: { sv: 'Från Campbellocking till Locking', en: 'From Campbellocking to Locking', fr: 'Du Campbellocking au Locking', fi: 'Campbellockingista Lockingiin', es: 'De Campbellocking a Locking', pt: 'De Campbellocking a Locking', ko: '캠벨락킹에서 락킹으로', ja: 'キャンベルロッキングからロッキングへ', zh: '从 Campbellocking 到 Locking' },
    title: { sv: 'Lockingens historia', en: 'The history of Locking', fr: 'L’histoire du Locking', fi: 'Lockingin historia', es: 'Historia del Locking', pt: 'História do Locking', ko: '락킹의 역사', ja: 'ロッキングの歴史', zh: 'Locking 的历史' },
    summary: {
      sv: 'Berättelsen om den ursprungliga eran, berättad genom pionjärernas egna perspektiv.',
      en: 'The story of the original era, told through the perspectives of its pioneers.',
      fr: 'L’histoire de la période fondatrice, racontée à travers les perspectives de ses pionniers.',
      fi: 'Alkuperäisen aikakauden tarina sen pioneerien näkökulmista kerrottuna.',
      es: 'La historia de los primeros años del Locking desde la perspectiva de los pioneros de aquella época.',
      pt: 'A história dos primeiros anos do Locking a partir da perspectiva dos pioneiros daquela época.',
      ko: '오리지널 시대의 이야기를 그 시대 파이오니어들의 관점으로 전합니다.',
      ja: 'オリジナル時代の物語を、その時代のパイオニアたちの視点から伝えます。',
      zh: '从那个时代先驱们的视角，讲述 Locking 最初时期的故事。',
    },
    group: 'history',
  },
  {
    slug: 'memorial',
    source: 'memorial.md',
    image: '/media/penguinscene.png',
    kicker: { sv: 'Vi minns', en: 'We remember', fr: 'Nous nous souvenons', fi: 'Me muistamme', es: 'Recordamos', pt: 'Nós lembramos', ko: '우리는 기억합니다', ja: '私たちは記憶します', zh: '我们铭记' },
    title: { sv: 'Till minne av legenderna', en: 'In memory of the legends', fr: 'À la mémoire des légendes', fi: 'Legendojen muistolle', es: 'En memoria de las leyendas', pt: 'Em memória das lendas', ko: '전설들을 기리며', ja: 'レジェンドたちを偲んで', zh: '纪念传奇人物' },
    summary: {
      sv: 'En plats för att hedra dem som formade kulturen och inte längre finns med oss.',
      en: 'A place to honor those who shaped the culture and are no longer with us.',
      fr: 'Un espace pour rendre hommage à celles et ceux qui ont façonné la culture et qui nous ont quittés.',
      fi: 'Paikka kunnioittaa kulttuuria muovanneita ihmisiä, jotka eivät enää ole keskuudessamme.',
      es: 'Un espacio para recordar a quienes dieron forma a esta cultura y ya no están con nosotros.',
      pt: 'Um espaço para lembrar quem ajudou a moldar esta cultura e já não está entre nós.',
      ko: '이 문화를 만들어 왔고 이제 우리 곁을 떠난 이들을 기리는 공간입니다.',
      ja: 'この文化を形づくり、今は私たちのもとを去った人々を称える場所です。',
      zh: '纪念那些塑造了这份文化、如今已经离开我们的人的空间。',
    },
    group: 'history',
  },
  {
    slug: 'groups-and-dancers',
    source: 'groups-and-dancers.md',
    image: '/media/33rpm.png',
    kicker: { sv: 'Kollektiv kraft', en: 'Collective power', fr: 'Force collective', fi: 'Yhteisön voima', es: 'Poder colectivo', pt: 'Força coletiva', ko: '함께 만든 힘', ja: 'ともに生み出した力', zh: '集体的力量' },
    title: { sv: 'Grupper & dansare', en: 'Groups & dancers', fr: 'Groupes & danseurs', fi: 'Ryhmät ja tanssijat', es: 'Grupos y bailarines', pt: 'Grupos e dançarinos', ko: '그룹 & 댄서', ja: 'グループ & ダンサー', zh: '团体与舞者' },
    summary: {
      sv: 'Möt grupperna, crews och individerna som utvecklade uttrycket under den ursprungliga eran.',
      en: 'Meet the groups, crews and individuals who developed the form during its original era.',
      fr: 'Découvrez les groupes, crews et personnalités qui ont développé cette forme durant sa période fondatrice.',
      fi: 'Tutustu ryhmiin, crew’eihin ja yksilöihin, jotka kehittivät ilmaisumuotoa sen alkuperäisellä aikakaudella.',
      es: 'Conoce los grupos, crews y bailarines individuales que desarrollaron la danza durante sus primeros años.',
      pt: 'Conheça os grupos, crews e dançarinos que desenvolveram a dança durante seus primeiros anos.',
      ko: '오리지널 시대에 이 표현을 발전시킨 그룹, 크루, 그리고 개별 댄서들을 만나보세요.',
      ja: 'オリジナル時代にこの表現を発展させたグループ、crew、そして個々のダンサーを紹介します。',
      zh: '认识那些在最初时期发展这门舞蹈的团体、crew 与个人舞者。',
    },
    group: 'history',
  },
  {
    slug: 'soul-train',
    source: 'soul-train.md',
    image: '/media/soultrain.png',
    kicker: { sv: 'Dansgolvet som förändrade allt', en: 'The dance floor that changed everything', fr: 'La piste de danse qui a tout changé', fi: 'Tanssilattia, joka muutti kaiken', es: 'La pista de baile que lo cambió todo', pt: 'A pista de dança que mudou tudo', ko: '모든 것을 바꾼 댄스 플로어', ja: 'すべてを変えたダンスフロア', zh: '改变一切的舞池' },
    title: { sv: 'Soul Train', en: 'Soul Train', fr: 'Soul Train', fi: 'Soul Train', es: 'Soul Train', pt: 'Soul Train', ko: 'Soul Train', ja: 'Soul Train', zh: 'Soul Train' },
    summary: {
      sv: 'Programmet som gav afroamerikansk musik, dans och kreativitet en nationell scen.',
      en: 'The show that gave African American music, dance and creativity a national stage.',
      fr: 'L’émission qui a offert une scène nationale à la musique, à la danse et à la créativité afro-américaines.',
      fi: 'Ohjelma, joka toi afroamerikkalaisen musiikin, tanssin ja luovuuden valtakunnalliselle näyttämölle.',
      es: 'El programa dio un escenario nacional a la música, la danza y la creatividad afroamericanas.',
      pt: 'O programa deu um palco nacional à música, à dança e à criatividade afro-americanas.',
      ko: '아프리카계 미국인의 음악, 춤, 창의성을 미국 전역의 무대로 가져간 프로그램입니다.',
      ja: 'アフリカ系アメリカ人の音楽、ダンス、創造性に全米規模の舞台を与えた番組です。',
      zh: '这档节目为美国非裔音乐、舞蹈与创造力提供了全国性的舞台。',
    },
    group: 'history',
  },
  {
    slug: 'wattstax',
    source: 'wattsstax.md',
    image: '/media/wattsstaxx.png',
    kicker: { sv: 'Musik, motstånd och gemenskap', en: 'Music, resistance and community', fr: 'Musique, résistance et communauté', fi: 'Musiikki, vastarinta ja yhteisö', es: 'Música, resistencia y comunidad', pt: 'Música, resistência e comunidade', ko: '음악, 저항 그리고 공동체', ja: '音楽、抵抗、コミュニティ', zh: '音乐、抗争与社群' },
    title: { sv: 'Wattstax', en: 'Wattstax', fr: 'Wattstax', fi: 'Wattstax', es: 'Wattstax', pt: 'Wattstax', ko: 'Wattstax', ja: 'Wattstax', zh: 'Wattstax' },
    summary: {
      sv: 'Konserten, eran och det kulturella sammanhang som gav kraft åt rörelsen.',
      en: 'The concert, era and cultural context that gave power to the movement.',
      fr: 'Le concert, l’époque et le contexte culturel qui ont donné sa force au mouvement.',
      fi: 'Konsertti, aikakausi ja kulttuurinen yhteys, jotka antoivat liikkeelle voimaa.',
      es: 'Explora el concierto, la época y el contexto cultural que dieron fuerza al movimiento.',
      pt: 'Explore o concerto, a época e o contexto cultural que deram força ao movimento.',
      ko: '그 움직임에 힘을 실어 준 콘서트와 시대, 그리고 문화적 맥락을 살펴봅니다.',
      ja: 'そのムーブメントに力を与えたコンサート、時代、文化的背景をたどります。',
      zh: '追溯赋予这场 movement 力量的音乐会、时代与文化背景。',
    },
    group: 'history',
  },
  {
    slug: 'pioneers',
    source: 'pioneers-page.md',
    image: '/media/thelockerslate.png',
    kicker: { sv: 'Original generation', en: 'Original generation', fr: 'Génération fondatrice', fi: 'Alkuperäinen sukupolvi', es: 'Generación original', pt: 'Geração original', ko: '오리지널 세대', ja: 'オリジナル世代', zh: '最初一代' },
    title: { sv: 'Pionjärerna', en: 'The pioneers', fr: 'Les pionniers', fi: 'Pioneerit', es: 'Los pioneros', pt: 'Os pioneiros', ko: '파이오니어들', ja: 'パイオニアたち', zh: '先驱们' },
    summary: {
      sv: 'Personerna vars steg, attityd, rytm och skaparkraft byggde grunden.',
      en: 'The people whose steps, attitude, rhythm and creativity built the foundation.',
      fr: 'Les personnes dont les pas, l’attitude, le rythme et la créativité ont posé les fondations.',
      fi: 'Ihmiset, joiden askeleet, asenne, rytmi ja luovuus loivat perustan.',
      es: 'Las personas que ayudaron a construir las bases del Locking con pasos, actitud, ritmo y creatividad.',
      pt: 'As pessoas que ajudaram a construir as bases do Locking com passos, atitude, ritmo e criatividade.',
      ko: '스텝, 태도, 리듬, 창의성으로 락킹의 토대를 만든 사람들입니다.',
      ja: 'ステップ、アティチュード、リズム、創造性によってロッキングの土台を築いた人々です。',
      zh: '这些人以 steps、attitude、rhythm 与创造力奠定了 Locking 的基础。',
    },
    group: 'knowledge',
  },
  {
    slug: 'the-legacy-keeper',
    image: '/media/skeeter-rabbit/skeeter-2005.jpg',
    imagePosition: 'center 34%',
    kicker: { sv: 'OG Skeeter Rabbit · Pionjär · Mentor · Historiebevarare', en: 'OG Skeeter Rabbit · Pioneer · Mentor · History keeper', fr: 'OG Skeeter Rabbit · Pionnier · Mentor · Gardien de l’histoire', fi: 'OG Skeeter Rabbit · Pioneeri · Mentori · Historian vaalija', es: 'OG Skeeter Rabbit · Pionero · Mentor · Guardián de la historia', pt: 'OG Skeeter Rabbit · Pioneiro · Mentor · Guardião da história', ko: 'OG Skeeter Rabbit · 파이오니어 · 멘토 · 역사의 수호자', ja: 'OG Skeeter Rabbit · パイオニア · メンター · 歴史の守り手', zh: 'OG Skeeter Rabbit · 先驱 · 导师 · 历史守护者' },
    title: { sv: 'The Legacy Keeper', en: 'The Legacy Keeper', fr: 'The Legacy Keeper', fi: 'The Legacy Keeper', es: 'The Legacy Keeper', pt: 'The Legacy Keeper', ko: 'The Legacy Keeper', ja: 'The Legacy Keeper', zh: 'The Legacy Keeper' },
    summary: {
      sv: 'James “OG Skeeter Rabbit” Higgins — dansaren, mentorn och rösten som såg till att fler av Lockingens människor och berättelser blev ihågkomna.',
      en: 'James “OG Skeeter Rabbit” Higgins — the dancer, mentor and voice who made sure more of Locking’s people and stories would be remembered.',
      fr: 'James « OG Skeeter Rabbit » Higgins — le danseur, mentor et gardien qui a veillé à préserver davantage de personnes et de récits du Locking.',
      fi: 'James ”OG Skeeter Rabbit” Higgins — tanssija, mentori ja ääni, joka auttoi säilyttämään yhä useampien Locking-ihmisten tarinat.',
      es: 'James “OG Skeeter Rabbit” Higgins: el bailarín, mentor y guardián que ayudó a preservar a más personas e historias del Locking.',
      pt: 'James “OG Skeeter Rabbit” Higgins: o dançarino, mentor e guardião que ajudou a preservar mais pessoas e histórias do Locking.',
      ko: 'James “OG Skeeter Rabbit” Higgins — 더 많은 Locking의 사람과 이야기가 기억되도록 지켜 온 댄서이자 멘토.',
      ja: 'James “OG Skeeter Rabbit” Higgins — Lockingを築いたより多くの人々と物語が記憶されるよう守ってきたダンサーでありメンター。',
      zh: 'James “OG Skeeter Rabbit” Higgins——让更多 Locking 人物与故事得以被记住的舞者、导师和守护者。',
    },
    group: 'knowledge',
  },
  {
    slug: 'the-line-captain',
    image: '/media/web_greg.png',
    imageFit: 'contain',
    imagePosition: 'right top',
    imageScale: 0.82,
    imageTransformOrigin: 'right top',
    kicker: { sv: 'Campbellock Jr. · Mentor · Pionjär', en: 'Campbellock Jr. · Mentor · Pioneer', fr: 'Campbellock Jr. · Mentor · Pionnier', fi: 'Campbellock Jr. · Mentori · Pioneeri', es: 'Campbellock Jr. · Mentor · Pionero', pt: 'Campbellock Jr. · Mentor · Pioneiro', ko: 'Campbellock Jr. · 멘토 · 파이오니어', ja: 'Campbellock Jr. · メンター · パイオニア', zh: 'Campbellock Jr. · 导师 · 先驱' },
    title: { sv: 'The Line Captain', en: 'The Line Captain', fr: 'The Line Captain', fi: 'The Line Captain', es: 'The Line Captain', pt: 'The Line Captain', ko: 'The Line Captain', ja: 'The Line Captain', zh: 'The Line Captain' },
    summary: {
      sv: 'Dave Gregory Pope, hans mentorskap och den pedagogiska struktur han byggde för Locking.',
      en: 'Dave Gregory Pope, his mentorship and the educational structure he built for Locking.',
      fr: 'Dave Gregory Pope, son rôle de mentor et la structure pédagogique qu’il a bâtie pour le Locking.',
      fi: 'Dave Gregory Pope, hänen mentorointinsa ja Lockingia varten rakentamansa opetusrakenne.',
      es: 'La historia de Dave Gregory Pope, su trabajo como mentor y la estructura educativa que creó para el Locking.',
      pt: 'A história de Dave Gregory Pope, seu trabalho como mentor e a estrutura educacional que criou para o Locking.',
      ko: 'Dave Gregory Pope와 그의 멘토링, 그리고 락킹을 위해 구축한 교육 체계를 소개합니다.',
      ja: 'Dave Gregory Pope、そのメンタリング、そしてロッキングのために築いた教育体系を紹介します。',
      zh: '介绍 Dave Gregory Pope、他的导师工作，以及他为 Locking 建立的教学体系。',
    },
    group: 'knowledge',
  },
  {
    slug: 'timeline',
    source: 'timeline.md',
    image: '/media/lockerslate70s.png',
    kicker: { sv: 'En kultur i rörelse', en: 'A culture in motion', fr: 'Une culture en mouvement', fi: 'Liikkeessä oleva kulttuuri', es: 'Una cultura en movimiento', pt: 'Uma cultura em movimento', ko: '움직이는 문화', ja: '動き続ける文化', zh: '不断流动的文化' },
    title: { sv: 'Tidslinjen', en: 'Timeline of Locking', fr: 'Chronologie du Locking', fi: 'Lockingin aikajana', es: 'Línea de tiempo del Locking', pt: 'Linha do tempo do Locking', ko: '락킹 타임라인', ja: 'ロッキングのタイムライン', zh: 'Locking 时间线' },
    summary: {
      sv: 'En kronologisk ingång till viktiga ögonblick, grupper och förändringar.',
      en: 'A chronological entry point to important moments, groups and changes.',
      fr: 'Un parcours chronologique à travers les moments, groupes et évolutions marquants.',
      fi: 'Kronologinen johdatus tärkeisiin hetkiin, ryhmiin ja muutoksiin.',
      es: 'Un recorrido cronológico por momentos, grupos y cambios importantes del Locking.',
      pt: 'Um percurso cronológico por momentos, grupos e mudanças importantes do Locking.',
      ko: '중요한 순간, 그룹, 변화를 시간의 흐름에 따라 살펴보는 출발점입니다.',
      ja: '重要な瞬間、グループ、変化を時系列でたどるための入口です。',
      zh: '按时间顺序进入 Locking 的重要时刻、团体与变化。',
    },
    group: 'knowledge',
  },
  {
    slug: 'steps-and-moves',
    source: 'steps-page.md',
    image: '/media/donflying.jpg',
    kicker: { sv: 'Grunden i rörelsen', en: 'The foundation in motion', fr: 'Les fondations en mouvement', fi: 'Perusta liikkeessä', es: 'Las bases en movimiento', pt: 'As bases em movimento', ko: '움직임 속의 기초', ja: '動きの中にある基礎', zh: '动作中的基础' },
    title: { sv: 'Steg & rörelser', en: 'Steps & moves', fr: 'Pas & mouvements', fi: 'Askeleet ja liikkeet', es: 'Pasos y movimientos', pt: 'Passos e movimentos', ko: '스텝 & 무브', ja: 'ステップ & ムーブ', zh: '步法与动作' },
    summary: {
      sv: 'Namn, ursprung och berättelser bakom rörelserna som formade Locking.',
      en: 'Names, origins and stories behind the moves that shaped Locking.',
      fr: 'Les noms, les origines et les histoires des mouvements qui ont façonné le Locking.',
      fi: 'Lockingia muovanneiden liikkeiden nimet, alkuperät ja tarinat.',
      es: 'Explora los nombres, orígenes e historias detrás de los movimientos que dieron forma al Locking.',
      pt: 'Explore os nomes, as origens e as histórias por trás dos movimentos que ajudaram a formar o Locking.',
      ko: '락킹을 형성한 무브들의 이름, 기원, 그리고 그 뒤의 이야기를 다룹니다.',
      ja: 'ロッキングを形づくったムーブの名称、起源、その背景にある物語を扱います。',
      zh: '探索塑造 Locking 的动作名称、来源与背后的故事。',
    },
    group: 'knowledge',
  },
  {
    slug: 'terminology',
    source: 'terminology.md',
    image: '/media/streetTerm.png',
    kicker: { sv: 'Språket bär kulturen', en: 'Language carries culture', fr: 'La langue porte la culture', fi: 'Kieli kantaa kulttuuria', es: 'El lenguaje lleva la cultura', pt: 'A linguagem carrega a cultura', ko: '언어에는 문화가 담깁니다', ja: '言葉は文化を運ぶ', zh: '语言承载文化' },
    title: { sv: 'Gatuspråk & terminologi', en: 'Street terminology', fr: 'Vocabulaire de rue', fi: 'Katukieli ja terminologia', es: 'Terminología callejera', pt: 'Terminologia de rua', ko: '스트리트 용어', ja: 'ストリート用語', zh: '街头术语' },
    summary: {
      sv: 'Ord och begrepp får sin betydelse från människorna, platserna och tiden där de uppstod.',
      en: 'Words and terms gain meaning from the people, places and time in which they emerged.',
      fr: 'Les mots et les termes prennent leur sens auprès des personnes, dans les lieux et à l’époque où ils sont apparus.',
      fi: 'Sanat ja käsitteet saavat merkityksensä ihmisistä, paikoista ja ajasta, joissa ne syntyivät.',
      es: 'Las palabras y los términos reciben su significado de las personas, lugares y épocas en las que nacieron.',
      pt: 'As palavras e os termos recebem significado das pessoas, dos lugares e das épocas em que surgiram.',
      ko: '말과 용어의 의미는 그것이 생겨난 사람들, 장소, 시대 속에서 만들어집니다.',
      ja: '言葉や用語の意味は、それが生まれた人々、場所、時代の中で形づくられます。',
      zh: '词语与术语的意义，由它们产生时的人、地点与时代共同塑造。',
    },
    group: 'knowledge',
  },
  {
    slug: 'social-party',
    source: 'social-party.md',
    image: '/media/socialdance.png',
    kicker: { sv: 'Före scenen fanns festen', en: 'Before the stage, there was the party', fr: 'Avant la scène, il y avait la fête', fi: 'Ennen näyttämöä oli juhla', es: 'Antes del escenario estaba la fiesta', pt: 'Antes do palco, existia a festa', ko: '무대보다 먼저 파티가 있었습니다', ja: 'ステージの前に、パーティーがあった', zh: '舞台之前，先有派对' },
    title: { sv: 'Social & Party Dances', en: 'Social & Party Dances', fr: 'Danses sociales & festives', fi: 'Social & Party Dances', es: 'Bailes sociales y de fiesta', pt: 'Danças sociais e de festa', ko: '소셜 & 파티 댄스', ja: 'ソーシャル & パーティーダンス', zh: '社交与派对舞蹈' },
    summary: {
      sv: 'Danserna, musiken och de sociala rummen som lade grunden till uttrycket.',
      en: 'The dances, music and social spaces that laid the foundation for the form.',
      fr: 'Les danses, la musique et les espaces sociaux qui ont posé les fondations de cette forme.',
      fi: 'Tanssit, musiikki ja sosiaaliset tilat, jotka loivat ilmaisumuodon perustan.',
      es: 'Explora las danzas, la música y los espacios sociales que ayudaron a construir las bases del Locking.',
      pt: 'Explore as danças, a música e os espaços sociais que ajudaram a construir as bases do Locking.',
      ko: '이 표현의 바탕이 된 춤, 음악, 그리고 사람들이 어울리던 소셜 공간을 살펴봅니다.',
      ja: 'この表現の土台となったダンス、音楽、人々が交流したソーシャルな場をたどります。',
      zh: '追溯为这门舞蹈奠定基础的舞蹈、音乐与社交空间。',
    },
    group: 'knowledge',
  },
  {
    slug: 'gogo-brothers',
    source: 'gogo-brothers.md',
    image: '/media/gogobrotherswatts.png',
    kicker: { sv: 'Handshake of brotherhood', en: 'Handshake of brotherhood', fr: 'Une poignée de main fraternelle', fi: 'Veljeyden kädenpuristus', es: 'El apretón de manos de la hermandad', pt: 'O aperto de mão da irmandade', ko: '형제애의 핸드셰이크', ja: '兄弟愛のハンドシェイク', zh: '兄弟情谊的握手' },
    title: { sv: 'GoGo & YoYo Brothers', en: 'GoGo & YoYo Brothers', fr: 'GoGo & YoYo Brothers', fi: 'GoGo & YoYo Brothers', es: 'GoGo & YoYo Brothers', pt: 'GoGo & YoYo Brothers', ko: 'GoGo & YoYo Brothers', ja: 'GoGo & YoYo Brothers', zh: 'GoGo & YoYo Brothers' },
    summary: {
      sv: 'Historien om gruppen, brödraskapet och vägen från Watts till Japan.',
      en: 'The story of the group, the brotherhood and the journey from Watts to Japan.',
      fr: 'L’histoire du groupe, de la fraternité et du voyage de Watts jusqu’au Japon.',
      fi: 'Tarina ryhmästä, veljeydestä ja matkasta Wattsista Japaniin.',
      es: 'La historia del grupo, la hermandad y un viaje que se extendió desde Watts hasta Japón.',
      pt: 'A história do grupo, da irmandade e de uma jornada que foi de Watts ao Japão.',
      ko: '그룹과 형제애, 그리고 Watts에서 일본으로 이어진 여정의 이야기입니다.',
      ja: 'グループ、兄弟愛、そしてWattsから日本へ続いた旅の物語です。',
      zh: '关于团体、兄弟情谊，以及从 Watts 延伸到日本的旅程。',
    },
    group: 'knowledge',
  },
  {
    slug: 'the-lockers',
    image: '/media/thelockerslline.png',
    kicker: { sv: 'Gruppen som förändrade dansscenen', en: 'The group that changed the dance scene', fr: 'Le groupe qui a transformé la scène de la danse', fi: 'Ryhmä, joka muutti tanssikentän', es: 'El grupo que cambió la escena de la danza', pt: 'O grupo que mudou a cena da dança', ko: '댄스 신을 바꾼 그룹', ja: 'ダンスシーンを変えたグループ', zh: '改变舞蹈场景的团体' },
    title: { sv: 'The Lockers', en: 'The Lockers', fr: 'The Lockers', fi: 'The Lockers', es: 'The Lockers', pt: 'The Lockers', ko: 'The Lockers', ja: 'The Lockers', zh: 'The Lockers' },
    summary: {
      sv: 'Från The Campbellockers till en av streetdansens mest inflytelserika grupper.',
      en: 'From The Campbellockers to one of street dance’s most influential groups.',
      fr: 'Des Campbellockers à l’un des groupes les plus influents de la street dance.',
      fi: 'The Campbellockersista yhdeksi street dancen vaikutusvaltaisimmista ryhmistä.',
      es: 'De The Campbellockers a uno de los grupos más influyentes de la historia del street dance.',
      pt: 'De The Campbellockers a um dos grupos mais influentes da história da street dance.',
      ko: 'The Campbellockers에서 스트리트 댄스 역사상 가장 영향력 있는 그룹 중 하나가 되기까지의 이야기입니다.',
      ja: 'The Campbellockersから、ストリートダンス史上もっとも影響力のあるグループの一つになるまでの物語です。',
      zh: '从 The Campbellockers 到街舞史上最具影响力的团体之一。',
    },
    group: 'knowledge',
  },
  {
    slug: 'stories',
    image: '/media/interview.webp',
    kicker: { sv: 'Röster från kulturen', en: 'Voices from the culture', fr: 'Les voix de la culture', fi: 'Kulttuurin ääniä', es: 'Voces de la cultura', pt: 'Vozes da cultura', ko: '문화 속 목소리', ja: '文化からの声', zh: '来自文化的声音' },
    title: { sv: 'Intervjuer & artiklar', en: 'Interviews & articles', fr: 'Entretiens & articles', fi: 'Haastattelut ja artikkelit', es: 'Entrevistas y artículos', pt: 'Entrevistas e artigos', ko: '인터뷰 & 기사', ja: 'インタビュー & 記事', zh: '访谈与文章' },
    summary: {
      sv: 'Coming soon.',
      en: 'Coming soon.',
      fr: 'Bientôt disponible.',
      fi: 'Tulossa pian.',
      es: 'Próximamente.',
      pt: 'Em breve.',
      ko: '곧 공개됩니다.',
      ja: '近日公開。',
      zh: '即将推出。',
    },
    group: 'main',
  },
  {
    slug: 'contact',
    image: '/media/wattshandshake.png',
    kicker: { sv: 'Hör av dig', en: 'Get in touch', fr: 'Écrivez-nous', fi: 'Ota yhteyttä', es: 'Ponte en contacto', pt: 'Entre em contato', ko: '연락해 주세요', ja: 'お問い合わせください', zh: '联系我们' },
    title: { sv: 'Kontakt', en: 'Contact', fr: 'Contact', fi: 'Yhteystiedot', es: 'Contacto', pt: 'Contato', ko: '연락처', ja: 'お問い合わせ', zh: '联系' },
    summary: {
      sv: 'Kontakta mig med frågor, rättelser eller berättelser till Locking.se.',
      en: 'Contact me with questions, corrections or stories for Locking.se.',
      fr: 'Contactez-nous pour poser une question, proposer une correction ou partager une histoire avec Locking.se.',
      fi: 'Ota yhteyttä, jos sinulla on kysymyksiä, korjauksia tai Locking.se-sivustolle sopiva tarina.',
      es: 'Si tienes preguntas sobre Locking.se, alguna corrección o una historia que quieras compartir, ponte en contacto con nosotros.',
      pt: 'Se você tiver perguntas sobre a Locking.se, correções ou uma história que queira compartilhar, entre em contato comigo.',
      ko: 'Locking.se에 관한 질문, 정정 사항, 또는 나누고 싶은 이야기가 있다면 연락해 주세요.',
      ja: 'Locking.seについての質問、訂正、または共有したい物語があればお問い合わせください。',
      zh: '如有关于 Locking.se 的问题、订正或希望分享的故事，请联系我们。',
    },
    group: 'main',
  },
];

export const pageBySlug = new Map(contentPages.map((page) => [page.slug, page]));

export const menuGroups = {
  history: contentPages.filter((page) => page.group === 'history'),
  knowledge: contentPages.filter((page) => page.group === 'knowledge'),
};
